version: '3.8 '
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=repapp
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      # copy the sql script to fill tables
      - ./init/data.sql:/docker-entrypoint-initdb.d/02-data.sql